package servidigital;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author José Tendero
 */
public final class Inicio extends JFrameConFondo {
    private final Dimension D;
    /** Creates new form Inicio */
    public Inicio() {
        initComponents();
        D = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize((int)(D.width * 0.8), (int)(D.height * 0.85));
        this.setIconImage(new ImageIcon(getClass().getResource("/servidigital/imagenes/IconoVentanas.png")).getImage());
        setLocationRelativeTo(null);
        setImagen("/servidigital/imagenes/ServiDigital.png");
        if(!Usuario.Permitido[1]) mnuClientes.setEnabled(false);
        if(!Usuario.Permitido[2]) mnuTiendas.setEnabled(false);
        if(!Usuario.Permitido[3]) mnuSoportistas.setEnabled(false);
        if(!Usuario.Permitido[4]) mnuGenerarCaso.setEnabled(false);
        if(!Usuario.Permitido[5]) mnuAdmCasos.setEnabled(false);
        if(!Usuario.Permitido[6]) mnuCategorias.setEnabled(false);
        if(!Usuario.Permitido[8]) mnuRepuestos.setEnabled(false);
//        if(!Usuario.Permitido[10]) mnuDepositos.setEnabled(false);
        if(!Usuario.Permitido[12]) mnuReimprimir.setEnabled(false);
        if(!Usuario.Permitido[13]) mnuAjustes.setEnabled(false);
        if(!Usuario.Permitido[14]) mnuCargos.setEnabled(false);
        if(!Usuario.Permitido[15]) mnuDescargos.setEnabled(false);
//        if(!Usuario.Permitido[16]) mnuTraslado.setEnabled(false);
        if(!Usuario.Permitido[17]) mnuRepClie.setEnabled(false);
        if(!Usuario.Permitido[18]) mnuCasoMarca.setEnabled(false);
        if(!Usuario.Permitido[19]) mnuCasoEquipo.setEnabled(false);
        if(!Usuario.Permitido[20]) mnuCasoCliente.setEnabled(false);
        if(!Usuario.Permitido[21]) mnuCasoDiagnostico.setEnabled(false);
        if(!Usuario.Permitido[23]) {
            mnuInventario.setEnabled(false);
            mnuConteo.setEnabled(false);
        }
        if(!Usuario.Permitido[24]) mnuMovimiento.setEnabled(false);
        if(!Usuario.Permitido[25]) mnuCategUsu.setEnabled(false);
        if(!Usuario.Permitido[27]) mnuUsuarios.setEnabled(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministrar = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuTiendas = new javax.swing.JMenuItem();
        mnuSoportistas = new javax.swing.JMenuItem();
        mnuCategorias = new javax.swing.JMenuItem();
        mnuRepuestos = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        mnuGenerarCaso = new javax.swing.JMenuItem();
        mnuAdmCasos = new javax.swing.JMenuItem();
        mnuOperaciones = new javax.swing.JMenu();
        mnuCargos = new javax.swing.JMenuItem();
        mnuDescargos = new javax.swing.JMenuItem();
        mnuAjustes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuReimprimir = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        mnuRepClie = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuCasoMarca = new javax.swing.JMenuItem();
        mnuCasoEquipo = new javax.swing.JMenuItem();
        mnuCasoCliente = new javax.swing.JMenuItem();
        mnuCasoDiagnostico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuInventario = new javax.swing.JMenuItem();
        mnuMovimiento = new javax.swing.JMenuItem();
        mnuConteo = new javax.swing.JMenuItem();
        mnuCategUsu = new javax.swing.JMenu();
        menuCategusu = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAcerca = new javax.swing.JMenuItem();
        mnuManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Gestión de Garantías");
        setIconImage(getIconImage());
        setIconImages(null);

        menuAdministrar.setText("Archivo");

        mnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico-Sculture.gif"))); // NOI18N
        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        menuAdministrar.add(mnuClientes);

        mnuTiendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        mnuTiendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_transferencia.jpg"))); // NOI18N
        mnuTiendas.setText("Sucursales");
        mnuTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTiendasActionPerformed(evt);
            }
        });
        menuAdministrar.add(mnuTiendas);

        mnuSoportistas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        mnuSoportistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/procesar.png"))); // NOI18N
        mnuSoportistas.setText("Empresas");
        mnuSoportistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSoportistasActionPerformed(evt);
            }
        });
        menuAdministrar.add(mnuSoportistas);

        mnuCategorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, 0));
        mnuCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/reports.png"))); // NOI18N
        mnuCategorias.setText("Categorías");
        mnuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriasActionPerformed(evt);
            }
        });
        menuAdministrar.add(mnuCategorias);

        mnuRepuestos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        mnuRepuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/tools.png"))); // NOI18N
        mnuRepuestos.setText("Repuestos");
        mnuRepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepuestosActionPerformed(evt);
            }
        });
        menuAdministrar.add(mnuRepuestos);
        menuAdministrar.add(jSeparator3);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/categrep.png"))); // NOI18N
        jMenuItem1.setText("Configurar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAdministrar.add(jMenuItem1);
        menuAdministrar.add(jSeparator1);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_clientes.gif"))); // NOI18N
        jMenuItem9.setText("Desconectar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuAdministrar.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_cerrar.png"))); // NOI18N
        jMenuItem10.setText("Salir");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuAdministrar.add(jMenuItem10);

        jMenuBar1.add(menuAdministrar);

        menuProcesos.setText("Procesos");

        mnuGenerarCaso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuGenerarCaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_add.png"))); // NOI18N
        mnuGenerarCaso.setText("Generar Nuevo Caso");
        mnuGenerarCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGenerarCasoActionPerformed(evt);
            }
        });
        menuProcesos.add(mnuGenerarCaso);

        mnuAdmCasos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mnuAdmCasos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/lupa.png"))); // NOI18N
        mnuAdmCasos.setText("Buscar Caso");
        mnuAdmCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdmCasosActionPerformed(evt);
            }
        });
        menuProcesos.add(mnuAdmCasos);

        mnuOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_transferencia.jpg"))); // NOI18N
        mnuOperaciones.setText("Operaciones");

        mnuCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_add.png"))); // NOI18N
        mnuCargos.setText("Cargo de Repuestos");
        mnuCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCargosActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mnuCargos);

        mnuDescargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_cerrar.png"))); // NOI18N
        mnuDescargos.setText("Descargo de Repuestos");
        mnuDescargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDescargosActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mnuDescargos);

        mnuAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/tools.png"))); // NOI18N
        mnuAjustes.setText("Ajuste de Existencias");
        mnuAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAjustesActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mnuAjustes);
        mnuOperaciones.add(jSeparator2);

        mnuReimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/reports.png"))); // NOI18N
        mnuReimprimir.setText("Reimprimir Operacion");
        mnuReimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReimprimirActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mnuReimprimir);

        menuProcesos.add(mnuOperaciones);

        jMenuBar1.add(menuProcesos);

        menuReportes.setText("Reportes");

        mnuRepClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico-Sculture.gif"))); // NOI18N
        mnuRepClie.setText("Clientes");
        mnuRepClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepClieActionPerformed(evt);
            }
        });
        menuReportes.add(mnuRepClie);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_add.png"))); // NOI18N
        jMenu1.setText("Casos de garantías");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/Report.png"))); // NOI18N
        jMenuItem6.setText("Global");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        mnuCasoMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/Report.png"))); // NOI18N
        mnuCasoMarca.setText("Marcas");
        mnuCasoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCasoMarcaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCasoMarca);

        mnuCasoEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/Report.png"))); // NOI18N
        mnuCasoEquipo.setText("Equipos");
        mnuCasoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCasoEquipoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCasoEquipo);

        mnuCasoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/Report.png"))); // NOI18N
        mnuCasoCliente.setText("Clientes");
        mnuCasoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCasoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCasoCliente);

        mnuCasoDiagnostico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/Report.png"))); // NOI18N
        mnuCasoDiagnostico.setText("Diagnósticos");
        mnuCasoDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCasoDiagnosticoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCasoDiagnostico);

        menuReportes.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/tools.png"))); // NOI18N
        jMenu2.setText("Repuestos");

        mnuInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mnuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/lupa.png"))); // NOI18N
        mnuInventario.setText("Inventario");
        mnuInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInventarioActionPerformed(evt);
            }
        });
        jMenu2.add(mnuInventario);

        mnuMovimiento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/generar.png"))); // NOI18N
        mnuMovimiento.setText("Mov. de Unidades");
        mnuMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimientoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuMovimiento);

        mnuConteo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnuConteo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/reports.png"))); // NOI18N
        mnuConteo.setText("Formato de Conteo");
        jMenu2.add(mnuConteo);

        menuReportes.add(jMenu2);

        jMenuBar1.add(menuReportes);

        mnuCategUsu.setText("Accesos");

        menuCategusu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCategusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_usuarios.png"))); // NOI18N
        menuCategusu.setText("Categorias");
        menuCategusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategusuActionPerformed(evt);
            }
        });
        mnuCategUsu.add(menuCategusu);

        mnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico-Sculture.gif"))); // NOI18N
        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        mnuCategUsu.add(mnuUsuarios);

        jMenuBar1.add(mnuCategUsu);

        mnuAyuda.setText("Ayuda");

        mnuAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnuAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/ico_clientes.gif"))); // NOI18N
        mnuAcerca.setText("Acerca de..");
        mnuAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAcerca);

        mnuManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_MASK));
        mnuManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/Report.png"))); // NOI18N
        mnuManual.setText("Manual de usuario");
        mnuManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManualActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuManual);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        //JOptionPane.showMessageDialog(null, "Clientes!");
        new Clientes(this,true).setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTiendasActionPerformed
        //JOptionPane.showMessageDialog(null, "Tiendas!");
        new Tiendas(this,true).setVisible(true);
    }//GEN-LAST:event_mnuTiendasActionPerformed

    private void mnuSoportistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSoportistasActionPerformed
        //JOptionPane.showMessageDialog(null, "Tecnicos!");
        new Soportistas(this,true).setVisible(true);
    }//GEN-LAST:event_mnuSoportistasActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        dispose();
        new Login(this,true).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void mnuGenerarCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGenerarCasoActionPerformed
        //JOptionPane.showMessageDialog(null, "Nuevo Caso!");
        new CasoCrear(this,true).setVisible(true);
    }//GEN-LAST:event_mnuGenerarCasoActionPerformed

    private void mnuAdmCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdmCasosActionPerformed
        new Casos(null,true).setVisible(true);
    }//GEN-LAST:event_mnuAdmCasosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new Rep_Tiendas(null,true,0).setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnuCasoDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCasoDiagnosticoActionPerformed
        new Rep_Tiendas(null,true,4).setVisible(true);
    }//GEN-LAST:event_mnuCasoDiagnosticoActionPerformed

    private void mnuCasoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCasoMarcaActionPerformed
        new Rep_Tiendas(null,true,1).setVisible(true);
    }//GEN-LAST:event_mnuCasoMarcaActionPerformed

    private void mnuCasoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCasoEquipoActionPerformed
        new Rep_Tiendas(null,true,2).setVisible(true);
    }//GEN-LAST:event_mnuCasoEquipoActionPerformed

    private void mnuCasoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCasoClienteActionPerformed
        new Rep_Tiendas(null,true,3).setVisible(true);
    }//GEN-LAST:event_mnuCasoClienteActionPerformed

    private void mnuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriasActionPerformed
        new Categreps(null,true).setVisible(true);
    }//GEN-LAST:event_mnuCategoriasActionPerformed

    private void mnuRepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepuestosActionPerformed
        new Repuestos(null,true).setVisible(true);
    }//GEN-LAST:event_mnuRepuestosActionPerformed

    private void mnuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInventarioActionPerformed
        new Rep_Repu_Inv(null,true).setVisible(true);
    }//GEN-LAST:event_mnuInventarioActionPerformed

    private void mnuAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "SERVIDIGITAL VERSIÓN 1.3.2", "Acerca de..", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuAcercaActionPerformed

    private void menuCategusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategusuActionPerformed
        new UsuarioCategorias(this, true).setVisible(true);
    }//GEN-LAST:event_menuCategusuActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        new Usuarios(this, true).setVisible(true);
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManualActionPerformed

    private void mnuMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMovimientoActionPerformed

    private void mnuReimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReimprimirActionPerformed
        new imprimirOperaciones(null,true).setVisible(true);
    }//GEN-LAST:event_mnuReimprimirActionPerformed

    private void mnuAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAjustesActionPerformed
        new RepuestosAjuste(null,true).setVisible(true);
    }//GEN-LAST:event_mnuAjustesActionPerformed

    private void mnuDescargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDescargosActionPerformed
        new RepuestosDescargo(null,true).setVisible(true);
    }//GEN-LAST:event_mnuDescargosActionPerformed

    private void mnuCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCargosActionPerformed
        new RepuestosCargo(null,true).setVisible(true);
    }//GEN-LAST:event_mnuCargosActionPerformed

    private void mnuRepClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepClieActionPerformed
        new Rep_Clientes(null,true).setVisible(true);
    }//GEN-LAST:event_mnuRepClieActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu menuAdministrar;
    private javax.swing.JMenuItem menuCategusu;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem mnuAcerca;
    private javax.swing.JMenuItem mnuAdmCasos;
    private javax.swing.JMenuItem mnuAjustes;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuCargos;
    private javax.swing.JMenuItem mnuCasoCliente;
    private javax.swing.JMenuItem mnuCasoDiagnostico;
    private javax.swing.JMenuItem mnuCasoEquipo;
    private javax.swing.JMenuItem mnuCasoMarca;
    private javax.swing.JMenu mnuCategUsu;
    private javax.swing.JMenuItem mnuCategorias;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuConteo;
    private javax.swing.JMenuItem mnuDescargos;
    private javax.swing.JMenuItem mnuGenerarCaso;
    private javax.swing.JMenuItem mnuInventario;
    private javax.swing.JMenuItem mnuManual;
    private javax.swing.JMenuItem mnuMovimiento;
    private javax.swing.JMenu mnuOperaciones;
    private javax.swing.JMenuItem mnuReimprimir;
    private javax.swing.JMenuItem mnuRepClie;
    private javax.swing.JMenuItem mnuRepuestos;
    private javax.swing.JMenuItem mnuSoportistas;
    private javax.swing.JMenuItem mnuTiendas;
    private javax.swing.JMenuItem mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
