package servidigital;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author wiZa
 */
public class PanelFondo extends javax.swing.JPanel {

    private Image img;
    
    /** Creates new form PanelFondo */
    public PanelFondo() {
        
    }
    
    public PanelFondo(Dimension d, String Ubicacion) {
        this.setSize(d);
        if(Ubicacion != null) {
            img = new ImageIcon(getClass().getResource(Ubicacion)).getImage();
        }
    }

    public void setImagen(String Ubicacion) {
        if(Ubicacion != null) {
            img = new ImageIcon(getClass().getResource(Ubicacion)).getImage();
        }
        else {
            img = null;
        }
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        if(img != null) {
            g.drawImage(img, 0, 0, this.getSize().width, this.getSize().height, this);
            this.setOpaque(false);
        }
        else {
            setOpaque(true);
        }
        super.paint(g);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
