/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package servidigital;

import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author wiZa
 */
public class Rep_Tiendas extends javax.swing.JDialog {
    private final DefaultListModel Disponibles;
    private final DefaultListModel Seleccionados;
    private String Reporte;
    /**
     * Creates new form Rep_Tiendas
     * @param parent
     * @param modal
     * @param P
     */
    public Rep_Tiendas(java.awt.Frame parent, boolean modal, int P) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        dcDesde.setSelectedDate(new GregorianCalendar(new GregorianCalendar().get(Calendar.YEAR),0,1));
        dcHasta.setSelectedDate(new GregorianCalendar());
        Disponibles = cargarTiendas();
        Seleccionados = new DefaultListModel();
        lstDispo.setModel(Disponibles);
        lstSelec.setModel(Seleccionados);
        switch(P){
            case 1:
                chckMarcas.setSelected(true);
                break;
            case 2:
                chckEquipos.setSelected(true);
                break;
            case 3:
                chckClientes.setSelected(true);
                break;
            case 4:
                chckDiagnosticos.setSelected(true);
                break;
            default:
                chckGlobal.setSelected(true);
                break;
        }
    }
    public Rep_Tiendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        dcDesde.setSelectedDate(new GregorianCalendar(new GregorianCalendar().get(Calendar.YEAR),0,1));
        dcHasta.setSelectedDate(new GregorianCalendar());
        Disponibles = cargarTiendas();
        Seleccionados = new DefaultListModel();
        lstDispo.setModel(Disponibles);
        lstSelec.setModel(Seleccionados);
    }
    private DefaultListModel cargarTiendas() {
        DefaultListModel cmb = new DefaultListModel();
        try {
            Main.BD.Consultar("select nombre from tiendas");
            while(Main.BD.rslSet().next()) {
                cmb.addElement(Main.BD.rslSet().getString("nombre"));
            }
        }
        catch(SQLException Ex) {
            JOptionPane.showMessageDialog(this, Ex.getMessage());
        }
        return cmb;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dcDesde = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        dcHasta = new datechooser.beans.DateChooserCombo();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDispo = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSelec = new javax.swing.JList();
        btnAdd = new javax.swing.JButton();
        btnRem = new javax.swing.JButton();
        btnAddall = new javax.swing.JButton();
        btnRemall = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        chckEquipos = new javax.swing.JRadioButton();
        chckClientes = new javax.swing.JRadioButton();
        chckDiagnosticos = new javax.swing.JRadioButton();
        chckGlobal = new javax.swing.JRadioButton();
        chckMarcas = new javax.swing.JRadioButton();
        btnOK = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes - Tiendas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Desde:");

        dcDesde.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dcDesde.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 14));
    dcDesde.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dcDesdeOnSelectionChange(evt);
        }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setText("Hasta:");

    dcHasta.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 14));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dcDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGap(46, 46, 46)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dcHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dcHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(jLabel1)
                .addComponent(dcDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));

    lstDispo.setBackground(new java.awt.Color(255, 204, 204));
    lstDispo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    lstDispo.setModel(new javax.swing.AbstractListModel() {
        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
        public int getSize() { return strings.length; }
        public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(lstDispo);

    lstSelec.setBackground(new java.awt.Color(204, 255, 204));
    lstSelec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    lstSelec.setModel(new javax.swing.AbstractListModel() {
        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
        public int getSize() { return strings.length; }
        public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane2.setViewportView(lstSelec);

    btnAdd.setText(">");
    btnAdd.setToolTipText("Agregar");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddActionPerformed(evt);
        }
    });

    btnRem.setText("<");
    btnRem.setToolTipText("Remover");
    btnRem.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemActionPerformed(evt);
        }
    });

    btnAddall.setText(">>");
    btnAddall.setToolTipText("Agregar todo");
    btnAddall.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddallActionPerformed(evt);
        }
    });

    btnRemall.setText("<<");
    btnRemall.setToolTipText("Retirar todo");
    btnRemall.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemallActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddall, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addComponent(btnRemall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jScrollPane1)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(btnAdd)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnRem)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnAddall)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnRemall)
                    .addGap(10, 10, 10))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));

    buttonGroup1.add(chckEquipos);
    chckEquipos.setText("Equipos");

    buttonGroup1.add(chckClientes);
    chckClientes.setText("Clientes");

    buttonGroup1.add(chckDiagnosticos);
    chckDiagnosticos.setText("Diagnosticos");

    buttonGroup1.add(chckGlobal);
    chckGlobal.setSelected(true);
    chckGlobal.setText("Global");

    buttonGroup1.add(chckMarcas);
    chckMarcas.setText("Marcas");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(chckGlobal)
            .addGap(18, 18, 18)
            .addComponent(chckMarcas)
            .addGap(18, 18, 18)
            .addComponent(chckEquipos)
            .addGap(18, 18, 18)
            .addComponent(chckClientes)
            .addGap(18, 18, 18)
            .addComponent(chckDiagnosticos)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(chckEquipos)
                .addComponent(chckClientes)
                .addComponent(chckDiagnosticos)
                .addComponent(chckGlobal)
                .addComponent(chckMarcas))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/reports.png"))); // NOI18N
    btnOK.setText("Visualizar");
    btnOK.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnOKActionPerformed(evt);
        }
    });

    btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/btnCerrar.png"))); // NOI18N
    btnAtras.setText("Atrás");
    btnAtras.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAtrasActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 6, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(85, 85, 85)
            .addComponent(btnAtras)
            .addGap(59, 59, 59)
            .addComponent(btnOK)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnOK)
                .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dcDesdeOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dcDesdeOnSelectionChange
        
    }//GEN-LAST:event_dcDesdeOnSelectionChange

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(lstDispo.getSelectedIndex() >= 0) {
            Seleccionados.addElement(Disponibles.remove(lstDispo.getSelectedIndex()));
        }
        else JOptionPane.showMessageDialog(null, "Debe seleccionar una tienda del panel izquierdo");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemActionPerformed
        if(lstSelec.getSelectedIndex() >= 0) {
            Disponibles.addElement(Seleccionados.remove(lstSelec.getSelectedIndex()));
        }
        else JOptionPane.showMessageDialog(null, "Debe seleccionar una tienda del panel derecho");
    }//GEN-LAST:event_btnRemActionPerformed

    private void btnAddallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddallActionPerformed
        while(Disponibles.getSize() > 0) {
            Seleccionados.addElement(Disponibles.remove(0));
        }
    }//GEN-LAST:event_btnAddallActionPerformed

    private void btnRemallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemallActionPerformed
        while(Seleccionados.getSize() > 0) {
            Disponibles.addElement(Seleccionados.remove(0));
        }
    }//GEN-LAST:event_btnRemallActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String Ti = ".";
        if(Seleccionados.getSize() > 0) {
            for(int i = 0; i < Seleccionados.getSize(); i++) {
                Ti = Ti + Seleccionados.getElementAt(i).toString() + ".";
            }
            if(this.chckGlobal.isSelected()) Reporte = "/Reportes/tiendasGlobal.jasper";
            if(this.chckMarcas.isSelected()) Reporte = "/Reportes/tiendasMarcas.jasper";
            if(this.chckEquipos.isSelected()) Reporte = "/Reportes/tiendasEquipos.jasper";
            if(this.chckClientes.isSelected()) Reporte = "/Reportes/tiendasClientes.jasper";
            if(this.chckDiagnosticos.isSelected()) Reporte = "/Reportes/tiendasDiagnosticos.jasper";
            Map P = new HashMap();
            P.put("desde", dcDesde.getSelectedDate().getTime());
            P.put("hasta", dcHasta.getSelectedDate().getTime());
            P.put("ubicaciones", Ti);
            new Reporte(Reporte,P).runReporte("Casos por tiendas", true);
        }
        else JOptionPane.showMessageDialog(null, "Debe seleccionar al menos una tienda para este reporte");
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rep_Tiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rep_Tiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rep_Tiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rep_Tiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Rep_Tiendas dialog = new Rep_Tiendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddall;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRem;
    private javax.swing.JButton btnRemall;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chckClientes;
    private javax.swing.JRadioButton chckDiagnosticos;
    private javax.swing.JRadioButton chckEquipos;
    private javax.swing.JRadioButton chckGlobal;
    private javax.swing.JRadioButton chckMarcas;
    private datechooser.beans.DateChooserCombo dcDesde;
    private datechooser.beans.DateChooserCombo dcHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstDispo;
    private javax.swing.JList lstSelec;
    // End of variables declaration//GEN-END:variables
}
