/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidigital;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class Rep_Repu_Inv extends javax.swing.JDialog {
    private final DefaultListModel lst;
    private final DefaultListModel sel;
    private final DefaultListModel lstD;
    private final DefaultListModel selD;
    private String Reporte;
    /**
     * Creates new form Rep_Repu_Inv
     * @param parent
     * @param modal
     */
    public Rep_Repu_Inv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        try {
            Main.BD.Consultar("select * from categrep");
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Reportes.Repuestos.Inventario", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        lst = Main.BD.Lista("nombre");
        sel = new DefaultListModel();
        lstCategorias.setModel(lst);
        selCategorias.setModel(sel);
        
        try {
            Main.BD.Consultar("select * from depositos");
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Reportes.Repuestos.Inventario", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        lstD = Main.BD.Lista("codigo");
        selD = new DefaultListModel();
        lstDepositos.setModel(lstD);
        selDepositos.setModel(selD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        selCategorias = new javax.swing.JList();
        quiALL = new javax.swing.JButton();
        quiSelec = new javax.swing.JButton();
        addSelec = new javax.swing.JButton();
        addALL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstDepositos = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        selDepositos = new javax.swing.JList();
        addALL1 = new javax.swing.JButton();
        addSelec1 = new javax.swing.JButton();
        quiSelec1 = new javax.swing.JButton();
        quiALL1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurar reporte");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/btnCerrar.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servidigital/imagenes/reports.png"))); // NOI18N
        btnOK.setText("Visualizar");
        btnOK.setHideActionText(true);
        btnOK.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        lstCategorias.setBackground(new java.awt.Color(255, 204, 204));
        lstCategorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstCategorias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstCategorias);

        selCategorias.setBackground(new java.awt.Color(204, 255, 204));
        selCategorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        selCategorias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1", "2" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(selCategorias);

        quiALL.setBackground(new java.awt.Color(255, 204, 204));
        quiALL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quiALL.setText("<<");
        quiALL.setToolTipText("Retira todas");
        quiALL.setFocusable(false);
        quiALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiALLActionPerformed(evt);
            }
        });

        quiSelec.setBackground(new java.awt.Color(255, 204, 204));
        quiSelec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quiSelec.setText("<");
        quiSelec.setToolTipText("Retira seleccion");
        quiSelec.setFocusable(false);
        quiSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiSelecActionPerformed(evt);
            }
        });

        addSelec.setBackground(new java.awt.Color(204, 255, 204));
        addSelec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addSelec.setText(">");
        addSelec.setToolTipText("Agrega seleccion");
        addSelec.setFocusable(false);
        addSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSelecActionPerformed(evt);
            }
        });

        addALL.setBackground(new java.awt.Color(204, 255, 204));
        addALL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addALL.setText(">>");
        addALL.setToolTipText("Agrega todas");
        addALL.setFocusable(false);
        addALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addALLActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione categorías a reflejar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione depósitos");

        lstDepositos.setBackground(new java.awt.Color(255, 204, 204));
        lstDepositos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstDepositos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstDepositos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lstDepositos);

        selDepositos.setBackground(new java.awt.Color(204, 255, 204));
        selDepositos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        selDepositos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1", "2" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(selDepositos);

        addALL1.setBackground(new java.awt.Color(204, 255, 204));
        addALL1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addALL1.setText(">>");
        addALL1.setToolTipText("Agrega todas");
        addALL1.setFocusable(false);
        addALL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addALL1ActionPerformed(evt);
            }
        });

        addSelec1.setBackground(new java.awt.Color(204, 255, 204));
        addSelec1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addSelec1.setText(">");
        addSelec1.setToolTipText("Agrega seleccion");
        addSelec1.setFocusable(false);
        addSelec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSelec1ActionPerformed(evt);
            }
        });

        quiSelec1.setBackground(new java.awt.Color(255, 204, 204));
        quiSelec1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quiSelec1.setText("<");
        quiSelec1.setToolTipText("Retira seleccion");
        quiSelec1.setFocusable(false);
        quiSelec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiSelec1ActionPerformed(evt);
            }
        });

        quiALL1.setBackground(new java.awt.Color(255, 204, 204));
        quiALL1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quiALL1.setText("<<");
        quiALL1.setToolTipText("Retira todas");
        quiALL1.setFocusable(false);
        quiALL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiALL1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(quiALL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quiSelec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addSelec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addALL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(quiALL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quiSelec1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addSelec1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addALL1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(btnOK)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addALL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSelec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quiSelec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quiALL))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(addALL1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addSelec1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(quiSelec1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(quiALL1))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnAtras))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String Cat = ".";
        String Dep = ".";
        if(sel.getSize() > 0 && selD.getSize() > 0) {
            for(int i = 0; i < selD.getSize(); i++) {
                Dep = Dep + selD.getElementAt(i).toString() + ".";
            }
            for(int i = 0; i < sel.getSize(); i++) {
                Cat = Cat + sel.getElementAt(i).toString() + ".";
            }
            Reporte = "repuestosInv.jasper";
            Map P = new HashMap();
            P.put("categorias", Cat);
            P.put("ubicaciones", Dep);
            new Reporte(Reporte,P).runReporte("Inventario de Articulos", true);
        }
        else JOptionPane.showMessageDialog(null, "Debe seleccionar categorias y depositos");
    }//GEN-LAST:event_btnOKActionPerformed

    private void quiALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiALLActionPerformed
        int j = sel.getSize();
        for(int i = 0; i < j; i++) {
            lst.addElement(sel.elementAt(0));
            sel.remove(0);
        }
    }//GEN-LAST:event_quiALLActionPerformed

    private void quiSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiSelecActionPerformed
        if(!selCategorias.isSelectionEmpty()) {
            lst.addElement(sel.elementAt(selCategorias.getSelectedIndex()));
            sel.remove(selCategorias.getSelectedIndex());
        }
    }//GEN-LAST:event_quiSelecActionPerformed

    private void addSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSelecActionPerformed
        if(!lstCategorias.isSelectionEmpty()) {
            sel.addElement(lst.elementAt(lstCategorias.getSelectedIndex()));
            lst.remove(lstCategorias.getSelectedIndex());
        }
    }//GEN-LAST:event_addSelecActionPerformed

    private void addALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addALLActionPerformed
        int j = lst.getSize();
        for(int i = 0; i < j; i++) {
            sel.addElement(lst.elementAt(0));
            lst.remove(0);
        }
    }//GEN-LAST:event_addALLActionPerformed

    private void addALL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addALL1ActionPerformed
        int j = lstD.getSize();
        for(int i = 0; i < j; i++) {
            selD.addElement(lstD.elementAt(0));
            lstD.remove(0);
        }
    }//GEN-LAST:event_addALL1ActionPerformed

    private void addSelec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSelec1ActionPerformed
        if(!lstDepositos.isSelectionEmpty()) {
            selD.addElement(lstD.elementAt(lstDepositos.getSelectedIndex()));
            lstD.remove(lstDepositos.getSelectedIndex());
        }
    }//GEN-LAST:event_addSelec1ActionPerformed

    private void quiSelec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiSelec1ActionPerformed
        if(!selDepositos.isSelectionEmpty()) {
            lstD.addElement(selD.elementAt(selDepositos.getSelectedIndex()));
            selD.remove(selDepositos.getSelectedIndex());
        }
    }//GEN-LAST:event_quiSelec1ActionPerformed

    private void quiALL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiALL1ActionPerformed
        int j = selD.getSize();
        for(int i = 0; i < j; i++) {
            lstD.addElement(selD.elementAt(0));
            selD.remove(0);
        }
    }//GEN-LAST:event_quiALL1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rep_Repu_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rep_Repu_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rep_Repu_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rep_Repu_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Rep_Repu_Inv dialog = new Rep_Repu_Inv(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addALL;
    private javax.swing.JButton addALL1;
    private javax.swing.JButton addSelec;
    private javax.swing.JButton addSelec1;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList lstCategorias;
    private javax.swing.JList lstDepositos;
    private javax.swing.JButton quiALL;
    private javax.swing.JButton quiALL1;
    private javax.swing.JButton quiSelec;
    private javax.swing.JButton quiSelec1;
    private javax.swing.JList selCategorias;
    private javax.swing.JList selDepositos;
    // End of variables declaration//GEN-END:variables
}
